# Updating Online Spreadsheets

This script will demonstrate how to upload the contents of a DataFrame into a Google Sheets file using Python's `gspread` and `gspread-dataframe` libraries. This is a convenient option for sharing your output with others, especially if you need to update that output on a regular basis.

The Google Sheets worksheet that this script will update can be found at https://docs.google.com/spreadsheets/d/17aDJ3mg49-n0IEnDgN7ZB85pO87fiUpkZPULYDB8dmo/edit?usp=sharing .


## Prerequisites

1. Python's gspread library provides a very helpful overview of connecting to Google Sheets workbooks via a service account at https://docs.gspread.org/en/latest/oauth2.html#for-bots-using-service-account . (There are multiple ways to connect to workbooks, but I find the service account approach to be pretty straightforward.) Go ahead and complete these steps if you haven't already. (Note: I chose to save my service account key to a custom path rather than the default one specified in the documentation; that way, I could more easily work with multiple account keys on my computer.) Also make sure that, prior to enabling the Google Sheets and Google Drive APIs, the Google Cloud project that you want to use for this script has been selected.

2. If you also specified a custom path, you'll need to create a file called 'service_key_path.txt' within this folder that points to it. That way, the following cell will be able to read in its location for use within gspread functions. (Alternatively, you could simply replace the following cell's code with `service_key_path = (path_to_your_key)`. Or, if you're using the default key location, you can comment out this cell altogether.)

3. As noted in the gspread service account documentation, you'll need to give the email associated with your service account editor access to the Google Sheets workbook that you'd like your script to update. (This email is *not* the same as your regular Google Email; it will likely look something like accountname@cloudprojectname.iam.gserviceaccount.com. You can find it within your service account file.

In [1]:
with open('service_key_path.txt') as file:
    service_key_path = file.read()

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.

In [2]:
import gspread
from gspread_dataframe import set_with_dataframe, get_as_dataframe
# From https://pypi.org/project/gspread-dataframe/

(If you're using gspread's default path, you can comment out the first line and then uncomment the following one.)

In [3]:
gc = gspread.service_account(filename=service_key_path)

# gc = gspread.service_account()

# (This code comes from
# # From https://docs.gspread.org/en/latest/index.html)

Importing additioal libraries:

(Note: the weather_import.py file being imported below derives from recent_weather_data.ipynb within the Automated_Notebooks section of Python for Nonprofits.)

In [4]:
import pandas as pd
pd.set_option('display.max_columns', 1000)
from weather_import import weather_import

## Importing new weather data for three Virginia weather stations; combining it with pre-existing data; and then saving a revised copy of this table to a .csv file:

In [5]:
data_folder = 'weather_data'

### Importing weather data for Charlottesville:

In [ ]:
print("Downloading KCHO data.")

In [6]:
weather_import(
    station_code = 'KCHO',
    data_folder = data_folder)

Original length of historical data file: 491
New length of historical data file: 491

### Importing weather data for Dulles International Airport:

In [ ]:
print("Downloading KIAD data.")

In [7]:
weather_import(
    station_code = 'KIAD',
    data_folder = data_folder)

Original length of historical data file: 70
New length of historical data file: 70

### Importing weather data for Winchester:

(This data appears to be recorded at 20-minute intervals rather than hourly ones.)

In [ ]:
print("Downloading KOKV data.")

In [8]:
weather_import(
    station_code = 'KOKV',
    data_folder = data_folder)

Original length of historical data file: 190
New length of historical data file: 190

## Reading these datasets into DataFrames:

In [9]:
df_weather_kcho = pd.read_csv(
    data_folder+'/'+'KCHO'+'_'
    +'historical_hourly_data_updated.csv')
df_weather_kcho.tail()

,Date,Day,Date/Time,Time,Time Zone,Wind (mph),Vis. (mi.),Weather,Sky Cond.,Temp,Dew Point,Relative Humidity,Wind Chill (Â°F),Heat Index (Â°F),altimeter (in),sea level (mb),1-Hour Precip,3-Hour Precip,6-Hour Precip,Data Retrieval Date,Obs_Month,Obs_Year
486,2024-11-21,21,2024-11-21 19:53,19:53,EST,SE 6,10.0,Fair,CLR,37.0,25.0,62.0,33.0,NaN,29.67,1004.8,0.0,0.0,0.0,2024-11-22,11,2024
487,2024-11-21,21,2024-11-21 20:53,20:53,EST,W 6,10.0,Partly Cloudy,SCT120,39.0,23.0,53.0,35.0,NaN,29.67,1004.8,0.0,0.0,0.0,2024-11-22,11,2024
488,2024-11-21,21,2024-11-21 21:53,21:53,EST,W 6,10.0,Fair,CLR,37.9,21.9,52.0,34.0,NaN,29.67,1004.9,0.0,0.0,0.0,2024-11-22,11,2024
489,2024-11-21,21,2024-11-21 22:53,22:53,EST,Vrbl 3,10.0,A Few Clouds,FEW060,36.0,21.0,55.0,NaN,NaN,29.67,1004.7,0.0,0.0,0.0,2024-11-22,11,2024
490,2024-11-21,21,2024-11-21 23:53,23:53,EST,Vrbl 3,10.0,A Few Clouds,FEW070,36.0,18.0,48.0,NaN,NaN,29.67,1004.7,0.0,0.0,0.0,2024-11-22,11,2024

In [10]:
df_weather_kiad = pd.read_csv(
    data_folder+'/'+'KIAD'+'_'
    +'historical_hourly_data_updated.csv')
df_weather_kiad.tail()

,Date,Day,Date/Time,Time,Time Zone,Wind (mph),Vis. (mi.),Weather,Sky Cond.,Temp,Dew Point,Relative Humidity,Wind Chill (Â°F),Heat Index (Â°F),altimeter (in),sea level (mb),1-Hour Precip,3-Hour Precip,6-Hour Precip,Data Retrieval Date,Obs_Month,Obs_Year
65,2024-11-21,21,2024-11-21 19:52,19:52,EST,W 8,10.0,Overcast,OVC065,41.0,33.1,73.0,36.0,NaN,29.65,1003.9,0.0,0.0,0.0,2024-11-22,11,2024
66,2024-11-21,21,2024-11-21 20:52,20:52,EST,W 13,10.0,A Few Clouds,FEW090,39.0,30.9,73.0,32.0,NaN,29.64,1003.9,0.0,0.0,0.0,2024-11-22,11,2024
67,2024-11-21,21,2024-11-21 21:52,21:52,EST,W 12,10.0,Partly Cloudy,SCT050,39.9,28.0,63.0,34.0,NaN,29.65,1004.1,0.0,0.0,0.0,2024-11-22,11,2024
68,2024-11-21,21,2024-11-21 22:52,22:52,EST,NW 22 G 28,10.0,Partly Cloudy and Breezy,SCT070,37.9,25.0,60.0,28.0,NaN,29.65,1003.9,0.0,0.0,0.0,2024-11-22,11,2024
69,2024-11-21,21,2024-11-21 23:52,23:52,EST,W 10,10.0,A Few Clouds,FEW070,36.0,24.1,62.0,29.0,NaN,29.63,1003.4,0.0,0.0,0.0,2024-11-22,11,2024

In [11]:
df_weather_kokv = pd.read_csv(
    data_folder+'/'+'KOKV'+'_'
    +'historical_hourly_data_updated.csv')
df_weather_kokv.tail()

,Date,Day,Date/Time,Time,Time Zone,Wind (mph),Vis. (mi.),Weather,Sky Cond.,Temp,Dew Point,Relative Humidity,Wind Chill (Â°F),Heat Index (Â°F),altimeter (in),sea level (mb),1-Hour Precip,3-Hour Precip,6-Hour Precip,Data Retrieval Date,Obs_Month,Obs_Year
185,2024-11-21,21,2024-11-21 22:35,22:35,EST,W 9,10.0,Fair,CLR,33.8,24.8,70.0,27.0,NaN,29.65,0.0,0.0,0.0,0.0,2024-11-22,11,2024
186,2024-11-21,21,2024-11-21 22:55,22:55,EST,W 9,10.0,Fair,CLR,33.8,23.0,65.0,27.0,NaN,29.65,0.0,0.0,0.0,0.0,2024-11-22,11,2024
187,2024-11-21,21,2024-11-21 23:15,23:15,EST,NW 13,10.0,Partly Cloudy,SCT035,33.8,23.0,65.0,25.0,NaN,29.64,0.0,0.0,0.0,0.0,2024-11-22,11,2024
188,2024-11-21,21,2024-11-21 23:35,23:35,EST,W 15 G 20,10.0,Fair,CLR,32.0,23.0,69.0,22.0,NaN,29.63,0.0,0.0,0.0,0.0,2024-11-22,11,2024
189,2024-11-21,21,2024-11-21 23:55,23:55,EST,W 12,10.0,Fair,CLR,32.0,23.0,69.0,24.0,NaN,29.62,0.0,0.0,0.0,0.0,2024-11-22,11,2024

## Importing these DataFrames into a Google Sheets workbook:

In order to export these datasets to a Google Sheets workbook, we'll first need to open that workbook with gspread. There are a few ways to do this (see https://docs.gspread.org/en/latest/user-guide.html#opening-a-spreadsheet for reference), but I like the `open_by_key()` option, which allows you--as the function's name suggests--to open a workbook using its key.

These keys are located within the center of each workbook URL. For instance, the full URL of the workbook I'll be updating is `https://docs.google.com/spreadsheets/d/17aDJ3mg49-n0IEnDgN7ZB85pO87fiUpkZPULYDB8dmo/edit?usp=sharing`, so the key--located in between the `/d/` component of that URL and the following `/`--is `17aDJ3mg49-n0IEnDgN7ZB85pO87fiUpkZPULYDB8dmo`.

In [6]:
wb = gc.open_by_key('17aDJ3mg49-n0IEnDgN7ZB85pO87fiUpkZPULYDB8dmo')
# Based on 
# https://docs.gspread.org/en/latest/user-guide.html#opening-a-spreadsheet
wb

Next, I'll select the 'KCHO' worksheet within this workbook, as that's the first one I'd like to update. I'll also clear out the current contents using `ws.clear()`; that way, only the latest DataFrame contents will appear within the spreadsheet after I call `set_with_dataframe` below. (If the most recent DataFrame is smaller than the previous version, parts of the previous one would still appear unless `ws.clear()` is called.

In [8]:
ws = wb.worksheet('KCHO')
# https://docs.gspread.org/en/latest/user-guide.html#opening-a-spreadsheet

In [13]:
ws.clear() 
ws

Finally, I'll call `set_with_dataframe` to export this DataFrame in its entirety to df_weather:

In [14]:
set_with_dataframe(ws, df_weather_kcho)
# Source: https://pypi.org/project/gspread-dataframe/

In order to confirm that this upload was successful, we can call `get_as_dataframe` to import the contents of the worksheet into a new DataFrame:

In [9]:
df_weather_from_ws = get_as_dataframe(ws)
df_weather_from_ws

,Date,Day,Date/Time,Time,Time Zone,Wind (mph),Vis. (mi.),Weather,Sky Cond.,Temp,Dew Point,Relative Humidity,Wind Chill (Â°F),Heat Index (Â°F),altimeter (in),sea level (mb),1-Hour Precip,3-Hour Precip,6-Hour Precip,Data Retrieval Date,Obs_Month,Obs_Year
0,2024-10-31,31.0,2024-10-31 2:53,2:53,EST,S 7,10.0,Fair,CLR,59.0,55.0,87.0,NaN,NaN,30.24,1023.5,0.0,0.0,0.0,2024-11-03,10.0,2024.0
1,2024-10-31,31.0,2024-10-31 3:53,3:53,EST,S 3,10.0,Fair,CLR,60.1,55.9,86.0,NaN,NaN,30.23,1023.1,0.0,0.0,0.0,2024-11-03,10.0,2024.0
2,2024-10-31,31.0,2024-10-31 5:53,5:53,EST,S 7,10.0,Fair,CLR,57.0,54.0,90.0,NaN,NaN,30.23,1023.1,0.0,0.0,0.0,2024-11-03,10.0,2024.0
3,2024-10-31,31.0,2024-10-31 6:53,6:53,EST,S 6,10.0,Fair,CLR,55.9,54.0,93.0,NaN,NaN,30.24,1023.5,0.0,0.0,0.0,2024-11-03,10.0,2024.0
4,2024-10-31,31.0,2024-10-31 7:53,7:53,EST,S 6,10.0,Fair,CLR,55.0,54.0,96.0,NaN,NaN,30.24,1023.5,0.0,0.0,0.0,2024-11-03,10.0,2024.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
511,2024-11-22,22.0,2024-11-22 18:53,18:53,EST,S 6,10.0,Overcast,SCT060 OVC070,42.1,26.1,53.0,39.0,NaN,29.55,1000.8,0.0,0.0,0.0,2024-11-22,11.0,2024.0
512,2024-11-22,22.0,2024-11-22 19:53,19:53,EST,Vrbl 3,10.0,Mostly Cloudy,BKN065 BKN080 BKN090,43.0,27.0,53.0,NaN,NaN,29.55,1000.6,0.0,0.0,0.0,2024-11-22,11.0,2024.0
513,2024-11-22,22.0,2024-11-22 20:53,20:53,EST,Calm,10.0,Overcast,FEW048 OVC060,44.1,28.0,53.0,NaN,NaN,29.55,1000.8,0.0,0.0,0.0,2024-11-22,11.0,2024.0
514,2024-11-22,22.0,2024-11-22 21:53,21:53,EST,NW 5,10.0,Overcast,BKN060 OVC070,45.0,28.9,54.0,43.0,NaN,29.55,1000.7,0.0,0.0,0.0,2024-11-22,11.0,2024.0
515,2024-11-22,22.0,2024-11-22 22:53,22:53,EST,NW 13 G 24,10.0,Partly Cloudy,SCT100,46.9,30.9,54.0,42.0,NaN,29.55,1000.6,0.0,0.0,0.0,2024-11-22,11.0,2024.0

In [10]:
df_weather_from_ws.query('`1-Hour Precip` > 0.0')

,Date,Day,Date/Time,Time,Time Zone,Wind (mph),Vis. (mi.),Weather,Sky Cond.,Temp,Dew Point,Relative Humidity,Wind Chill (Â°F),Heat Index (Â°F),altimeter (in),sea level (mb),1-Hour Precip,3-Hour Precip,6-Hour Precip,Data Retrieval Date,Obs_Month,Obs_Year
180,2024-11-07,7.0,2024-11-07 16:53,16:53,EST,NW 3,8.0,Light Rain,OVC050,69.1,64.9,87.0,NaN,NaN,30.07,1017.8,0.02,0.00,0.00,2024-11-07,11.0,2024.0
181,2024-11-07,7.0,2024-11-07 17:53,17:53,EST,SE 5,10.0,Mostly Cloudy,SCT065 BKN080 BKN110,71.1,64.9,81.0,NaN,NaN,30.07,1017.8,0.01,0.00,0.00,2024-11-07,11.0,2024.0
247,2024-11-10,10.0,2024-11-10 16:53,16:53,EST,SW 14 G 21,6.0,Light Rain,SCT036 BKN050 OVC060,53.1,41.0,64.0,NaN,NaN,30.11,1019.7,0.01,0.00,0.00,2024-11-10,11.0,2024.0
335,2024-11-14,14.0,2024-11-14 10:53,10:53,EST,NE 7,3.0,Light Rain,FEW049 SCT060 OVC075,42.1,35.1,76.0,38.0,NaN,30.20,1022.8,0.01,0.00,0.00,2024-11-17,11.0,2024.0
336,2024-11-14,14.0,2024-11-14 11:53,11:53,EST,N 5,3.0,Light Rain Fog/Mist,FEW029 BKN060 OVC075,42.1,37.9,85.0,40.0,NaN,30.15,1021.2,0.08,0.00,0.00,2024-11-17,11.0,2024.0
337,2024-11-14,14.0,2024-11-14 12:53,12:53,EST,N 5,4.0,Light Rain Fog/Mist,OVC023,41.0,39.0,93.0,38.0,NaN,30.12,1020.1,0.09,0.00,0.18,2024-11-17,11.0,2024.0
338,2024-11-14,14.0,2024-11-14 13:53,13:53,EST,NW 3,3.0,Light Rain Fog/Mist,OVC016,42.1,39.9,92.0,NaN,NaN,30.11,1019.9,0.05,0.00,0.00,2024-11-17,11.0,2024.0
339,2024-11-14,14.0,2024-11-14 14:53,14:53,EST,Calm,4.0,Light Rain Fog/Mist,OVC017,42.1,39.9,92.0,NaN,NaN,30.08,1018.8,0.09,0.00,0.00,2024-11-17,11.0,2024.0
340,2024-11-14,14.0,2024-11-14 15:53,15:53,EST,Calm,3.0,Light Rain Fog/Mist,BKN003 BKN050 OVC070,42.1,41.0,96.0,NaN,NaN,30.06,1018.3,0.13,0.27,0.00,2024-11-17,11.0,2024.0
341,2024-11-14,14.0,2024-11-14 16:53,16:53,EST,NW 5,5.0,Light Rain Fog/Mist,FEW003 OVC012,42.1,41.0,96.0,40.0,NaN,30.04,1017.4,0.05,0.00,0.00,2024-11-18,11.0,2024.0
342,2024-11-14,14.0,2024-11-14 17:53,17:53,EST,E 3,4.0,Light Rain Fog/Mist,BKN003 OVC011,43.0,41.0,93.0,NaN,NaN,30.03,1017.0,0.01,0.00,0.00,2024-11-18,11.0,2024.0
343,2024-11-14,14.0,2024-11-14 18:53,18:53,EST,Calm,3.0,Light Rain Fog/Mist,BKN003 OVC011,43.0,42.1,97.0,NaN,NaN,30.03,1017.1,0.02,0.00,0.35,2024-11-18,11.0,2024.0
346,2024-11-14,14.0,2024-11-14 21:53,21:53,EST,Calm,2.0,Light Rain Fog/Mist,BKN004 OVC007,44.1,42.1,93.0,NaN,NaN,30.00,1015.9,0.03,0.03,0.00,2024-11-18,11.0,2024.0
347,2024-11-14,14.0,2024-11-14 23:53,23:53,EST,Calm,3.0,Light Rain Fog/Mist,BKN003 OVC009,44.1,43.0,96.0,NaN,NaN,29.97,1014.8,0.03,0.00,0.00,2024-11-18,11.0,2024.0
348,2024-11-15,15.0,2024-11-15 0:53,0:53,EST,NE 5,4.0,Light Rain Fog/Mist,BKN005 OVC010,45.0,43.0,93.0,43.0,NaN,29.94,1014.0,0.02,0.00,0.12,2024-11-18,11.0,2024.0
463,2024-11-20,20.0,2024-11-20 18:53,18:53,EST,Calm,2.0,Light Rain Fog/Mist,BKN011 OVC029,55.9,55.0,97.0,NaN,NaN,29.62,1003.0,0.26,0.00,0.26,2024-11-22,11.0,2024.0
464,2024-11-20,20.0,2024-11-20 19:53,19:53,EST,NW 10 G 20,4.0,Light Rain Fog/Mist,SCT002 BKN043 OVC060,55.9,54.0,93.0,NaN,NaN,29.65,1003.9,0.06,0.00,0.00,2024-11-22,11.0,2024.0
465,2024-11-20,20.0,2024-11-20 20:53,20:53,EST,NW 9 G 24,10.0,Overcast,OVC055,51.1,39.0,64.0,NaN,NaN,29.70,1005.5,0.01,0.00,0.00,2024-11-22,11.0,2024.0

In [12]:
# df_weather_from_ws.to_dict()

## Performing the same data export steps for KIAD and KOKV data:

In [16]:
ws = wb.worksheet('KIAD')
ws.clear() 
set_with_dataframe(ws, df_weather_kiad)

ws = wb.worksheet('KOKV')
ws.clear() 
set_with_dataframe(ws, df_weather_kokv)

In [15]:
pd.DataFrame(data = {'x':[1, 2, 3, 4], 'y':[0, 3, 9, 7]})

   x  y
0  1  0
1  2  3
2  3  9
3  4  7